In [68]:
#Name - deepanshu jain



#!pip install numpy
#Array manipulation

# 1d array

import numpy as np

arr_1=np.array([1,2,4,3,7,5])
arr_1

array([1, 2, 4, 3, 7, 5])

In [69]:
#2d array

arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
#Empty array of size n having n garbage values

arr_3 = np.empty(5)
arr_3

array([1., 1., 1., 1., 1.])

In [71]:
#list of one
print(np.ones(6))
#array of one
print(np.array(np.ones(5)))
x=np.ones(5)
x

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.])

In [72]:
#List of zeroes
print(np.zeros(6))
#Zero matrix
np.array([np.zeros(2),np.zeros(2)])

[0. 0. 0. 0. 0. 0.]


array([[0., 0.],
       [0., 0.]])

In [81]:
#Identity matrix
print(np.eye(6))
n=int(input())
print(np.eye(n));np.eye(n)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.arange(1,60,5)
#Not arrange

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56])

In [75]:
#Indexing in array

x=np.arange(1,5,1)
print(x)
print(x[1])
x

[1 2 3 4]
2


array([1, 2, 3, 4])

In [76]:
#Slicing
x=np.array([1,2,4,5,7])
x[0:5:2]
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(y[0:2,0:2])
y[0:2,0:2]=10
print(y)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[10 10  3]
 [10 10  6]]


In [80]:
#createcopy of array
print(x)
x_copy=x[0:4]
np.array(x_copy)
print(x_copy)

print(x)
#So the original array will change if we change the copy array 
#Therefore we use x.copy() function
z_copy = x.copy()
print(z_copy)
z_copy[:]=5
print(z_copy)
print(x)

[1 2 4 5 7]
[1 2 4 5]
[1 2 4 5 7]
[1 2 4 5 7]
[5 5 5 5 5]
[1 2 4 5 7]


In [113]:
#reshaping the array
print(arr_2)
x=np.arange(0,25,1)
print(x)
x=x.reshape(5,5)
print(x)
print(arr_2.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 2]
 [3 4]
 [5 6]]


In [114]:
#Transposing arrays
print(x)
print("Transpose is ")
print(x.transpose())
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Transpose is 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [101]:
#Functions in array
x=np.arange(1,6,2)
y=np.arange(1,11,4)
print(x)
print(y)

#exponential of arrays
print(np.exp(x))
#square
print(np.square(x))
#square root
print(np.sqrt(x))
#cube root
print(np.cbrt(x))
#add
print(np.add(x,y))
#Subtraction
print(np.subtract(x,y))

[1 3 5]
[1 5 9]
[  2.71828183  20.08553692 148.4131591 ]
[ 1  9 25]
[1.         1.73205081 2.23606798]
[1.         1.44224957 1.70997595]
[ 2  8 14]
[ 0 -2 -4]


In [103]:
#numpy array processing functions
cond=np.array([True,True,False])
print(np.where(cond,x,y))

[1 3 9]


In [111]:
#random function
arr1=np.random.rand(7)
print(arr1)
#mean
print(arr1.mean())
#variance
print(arr1.var())
#standard deviation
print(arr1.std())
#sum
print(arr1.sum())
#sort
arr1.sort()
print(arr1)
#unique
arr2=["car","car","car","bike","car"]
np.unique(arr2)

[0.97889439 0.93139467 0.09552012 0.98536727 0.07552609 0.14379391
 0.73661432]
0.5638729653552652
0.16415935524993053
0.4051658367260627
3.9471107574868567
[0.07552609 0.09552012 0.14379391 0.73661432 0.93139467 0.97889439
 0.98536727]


array(['bike', 'car'], dtype='<U4')

In [184]:
import numpy

def getMinMax(arr):
    mini=[]
    maxi=[]
    print("Number of rows in array is ",len(arr))
    for i in range(len(arr)):
        mini.append(arr[i].min())
        maxi.append(arr[i].max())
    return mini,maxi
    
        
        
    
arr=np.random.randint(1,150,(10,10))
print("Arrray is \n",arr)
getMinMax(arr)




Arrray is 
 [[123  22  89 145  63 122  80 110 108 115]
 [  5  43   7  95  55 141  95  48 109  20]
 [ 60  22 107  32  86  21 131  22   9 135]
 [103  38  52  20  94 121 121 112  75 102]
 [ 49  64 134   5  48  18  87  23 134 120]
 [ 96   9 116  79   9 118   8  76  61 105]
 [135  60  12 116  60   3  27  54  76  91]
 [ 73  48 106 148  90  47  66  29  97 110]
 [ 54 116  74  30  78 139  11  94 140  67]
 [ 12  48  27  83 111 116  10   9  88   7]]
Number of rows in array is  10


([22, 5, 9, 20, 5, 8, 3, 29, 11, 7],
 [145, 141, 135, 121, 134, 118, 135, 148, 140, 116])

In [181]:


#getMinMax(arr)



Arrray is 
 [[ 25 142  16 108 138 107   8 107  21 101]
 [ 42 115  33 112  62 115  59  20  75  20]
 [ 94 117   4  97  32  98  19  72  36  14]
 [ 77  42  41 137  42  50 149  60  46   5]
 [ 30  48  77 115  39  93  78  83 133  31]
 [ 52  54 132  67 132  48   2 134 111  48]
 [134 101  65  86  77  76  51  85   9 147]
 [ 67  31 101  64  21  78  15  71 122 112]
 [ 32 112  11  50 125 131 105  57  79  89]
 [135  59 148 144   8  38  37  78  83 146]]
